env:
  global:
    secure: H+BYasgSxi3eDq6Nw17O+joRzYffbH5X2drt/ZX18JjYIkpwpGuB1bUEx+94Mdvq5uaISgUUDT6Kz4rE4d5iy/vtcflfW+AXuTVR4AOt3GqzxHZvJRJ24kccazFuSiH7wiYD1/7G/B6CV+etwu6dayKfIqAkauBEkdRzFldiSww=
  matrix:
  - PYTHON_VERSION=2
  - PYTHON_VERSION=3

install:
- wget https://raw.githubusercontent.com/jabooth/traviconda/master/traviconda.py -O traviconda.py
- python traviconda.py setup --python $PYTHON_VERSION --channel menpo
- export HDF5ABLE_VERSION=$(python traviconda.py version)
- export PATH=/home/travis/miniconda/bin:$PATH

script:
- python traviconda.py build --path ./conda --user menpo --key $BINSTAR_KEY

notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7599ff4870c99ba51310
    on_success: always
    on_failure: always
    on_start: never
