# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows
build: false

environment:
  matrix:
    - PYTHON_VERSION: 2
    - PYTHON_VERSION: 3

platform:
- x86
- x64

init:
- ps: Start-FileDownload 'https://raw.githubusercontent.com/jabooth/traviconda/master/traviconda.py' C:\\traviconda.py; echo "Done"
- cmd: python C:\\traviconda.py setup %PYTHON_VERSION% --channel menpo

install:
- cmd: C:\\Miniconda\\python C:\\traviconda.py auto ./conda --binstaruser menpo --binstarkey tehehe
