# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows
build: false

environment:
  matrix:
    - PYTHON_VERSION: 2
    - PYTHON_VERSION: 3

platform:
- x86
- x64

init:
- ps: Start-FileDownload 'https://raw.githubusercontent.com/jabooth/traviconda/master/traviconda.py' C:\\traviconda.py; echo "Done"
- cmd: python C:\\traviconda.py setup %PYTHON_VERSION% --channel menpo

install:
- ps: "git describe --tags"
- ps: "$HDF5ABLE_VERSION= python traviconda.py version; [Environment]::SetEnvironmentVariable(\"HDF5ABLE_VERSION\", $HDF5ABLE_VERSION, \"Machine\")"
- ps: "Get-ChildItem Env:"
- cmd: C:\\Miniconda\\python C:\\traviconda.py auto ./conda --binstaruser menpo --binstarkey tehehe
