package:
  name: hdf5able
  version: {{ environ['HDF5ABLE_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - h5py
    - pathlib # [not py3k]
    - enum    # [not py3k]
	
test:
  requires:
  - nose

  imports:
    - hdf5able

  commands:
    - python -c "import nose; nose.main()" -s hdf5able

about:
  home: https://github.com/menpo/hdf5able/
  license: BSD License
